### ISSUE TITLE
Error when enabling plugin.

### ISSUE THREAD

**Issue by ImranDoet** [ImranDoet/Flow#1]
`[01:09:47 ERROR]: Could not load 'plugins\Flow-1.3.0.jar' in folder 'plugins'
org.bukkit.plugin.InvalidDescriptionException: Invalid plugin.yml
        at org.bukkit.plugin.java.JavaPluginLoader.getPluginDescription(JavaPlug
inLoader.java:152) ~[spigot.jar:git-Spigot-3fb9445-2b6c9f4]
        at org.bukkit.plugin.SimplePluginManager.loadPlugins(SimplePluginManager
.java:133) [spigot.jar:git-Spigot-3fb9445-2b6c9f4]
        at org.bukkit.craftbukkit.v1_11_R1.CraftServer.loadPlugins(CraftServer.j
ava:301) [spigot.jar:git-Spigot-3fb9445-2b6c9f4]
        at org.bukkit.craftbukkit.v1_11_R1.CraftServer.reload(CraftServer.java:7
48) [spigot.jar:git-Spigot-3fb9445-2b6c9f4]
        at org.bukkit.Bukkit.reload(Bukkit.java:540) [spigot.jar:git-Spigot-3fb9
445-2b6c9f4]
        at org.bukkit.command.defaults.ReloadCommand.execute(ReloadCommand.java:
25) [spigot.jar:git-Spigot-3fb9445-2b6c9f4]
        at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:14
1) [spigot.jar:git-Spigot-3fb9445-2b6c9f4]
        at org.bukkit.craftbukkit.v1_11_R1.CraftServer.dispatchCommand(CraftServ
er.java:650) [spigot.jar:git-Spigot-3fb9445-2b6c9f4]
        at org.bukkit.craftbukkit.v1_11_R1.CraftServer.dispatchServerCommand(Cra
ftServer.java:636) [spigot.jar:git-Spigot-3fb9445-2b6c9f4]
        at net.minecraft.server.v1_11_R1.DedicatedServer.aM(DedicatedServer.java
:437) [spigot.jar:git-Spigot-3fb9445-2b6c9f4]
        at net.minecraft.server.v1_11_R1.DedicatedServer.D(DedicatedServer.java:
400) [spigot.jar:git-Spigot-3fb9445-2b6c9f4]
        at net.minecraft.server.v1_11_R1.MinecraftServer.C(MinecraftServer.java:
678) [spigot.jar:git-Spigot-3fb9445-2b6c9f4]
        at net.minecraft.server.v1_11_R1.MinecraftServer.run(MinecraftServer.jav
a:576) [spigot.jar:git-Spigot-3fb9445-2b6c9f4]
        at java.lang.Thread.run(Unknown Source) [?:1.8.0_131]
Caused by: java.io.FileNotFoundException: Jar does not contain plugin.yml
        ... 14 more`

**Comment by ImranDoet** [comment]
Didn't package plugin.yml or config.yml, oops.

**Comment by ImranDoet** [comment]
Fixed in the new update.
